# Generated by Django 3.0.2 on 2020-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
