version: '3'
services:
  app:
    build:
      dockerfile: docker/Dockerfile.app
      context: ./
    ports:
    - 8000:8000
    volumes:
    - ./:/opt/project
    command: python
    links:
      - postgres

  postgres:
    build:
      dockerfile: docker/Dockerfile.postgres
      context: ./
    ports:
    - 5432:5432
    restart: always
    volumes:
    - ./db-data:/var/lib/postgresql/data

