# Generated by Django 3.0.2 on 2020-02-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20200226_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quize_type',
        ),
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('quize_type', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quize')),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Enigma'),
        ),
    ]
