# Generated by Django 3.0.2 on 2020-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize_app', '0002_auto_20200312_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='answer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
