# Generated by Django 3.0.2 on 2020-03-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize_app', '0003_auto_20200313_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='riddle',
            name='quiz_type',
        ),
    ]
